apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: bruno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.1.4
        args: ["start-dev", "--import-realm"]
        ports:
        - containerPort: 9090
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: jdbc:postgresql://bruno-db:5432/keycloak
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: bruno-db.credentials.bruno_user
              key: username
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bruno-db.credentials.bruno_user
              key: password
