apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bruno
  namespace: flux-system
spec:
  interval: 1m
  path: "./k8s"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bruno-repo
  targetNamespace: bruno
